services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUBLIC_UMAMI_HOST: ${PUBLIC_UMAMI_HOST:-}
        PUBLIC_UMAMI_WEBSITE_ID: ${PUBLIC_UMAMI_WEBSITE_ID:-}
    restart: unless-stopped
    expose:
      - '80'
    networks:
      - wishfetch_default

networks:
  wishfetch_default:
    external: true
